// Mock data to simulate API response
export const getMockSummonerData = (
  gameName: string,
  tagLine: string,
  region: string
) => {
  return {
    accountId: "mock-account-123",
    rank: "Diamond II",
    leaguePoints: 75,
    winRate: 54,
    rankHistory: [
      { date: "2024-02-01", lp: 45 },
      { date: "2024-02-15", lp: 68 },
      { date: "2024-03-01", lp: 32 },
      { date: "2024-03-15", lp: 75 },
    ],
    championStats: [
      {
        championId: 103,
        championName: "Ahri",
        gamesPlayed: 45,
        winRate: 56,
        kda: "3.2/2.1/8.5",
      },
      {
        championId: 236,
        championName: "Lucian",
        gamesPlayed: 32,
        winRate: 52,
        kda: "4.1/3.2/6.3",
      },
      {
        championId: 25,
        championName: "Morgana",
        gamesPlayed: 28,
        winRate: 58,
        kda: "2.4/2.8/11.2",
      },
    ],
    matches: [
      {
        gameId: "MOCK1",
        gameCreation: Date.now() - 86400000, // 1 day ago
        gameDuration: 2345, // in seconds
        win: true,
        allyTeam: [
          {
            summonerName: gameName,
            championId: 103,
            championName: "Ahri",
            championLevel: 18,
            kills: 8,
            deaths: 3,
            assists: 12,
            items: [3157, 3089, 3020, 3165, 3135, 3139],
            spells: ["Flash", "Dot"],
            rank: "Diamond II",
            cs: 220,
            damage: 24500,
            runes: {
              primary: "7200_Domination",
              secondary: "7202_Sorcery",
              keystone: "Electrocute",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
        ],
        enemyTeam: [
          {
            summonerName: "Enemy1",
            championId: 245,
            championName: "Ekko",
            championLevel: 17,
            kills: 5,
            deaths: 7,
            assists: 6,
            items: [3157, 3089, 3020, 3165, 3135, 3139],
            spells: ["Flash", "Teleport"],
            rank: "Platinum I",
            cs: 200,
            damage: 23000,
            runes: {
              primary: "7202_Sorcery",
              secondary: "7200_Domination",
              keystone: "PhaseRush",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
          {
            summonerName: "Player2",
            championId: 236,
            championName: "Lucian",
            championLevel: 17,
            kills: 10,
            deaths: 5,
            assists: 8,
            items: [3153, 3087, 3006, 3072, 3031, 3139],
            spells: ["Flash", "Heal"],
            rank: "Platinum I",
            cs: 180,
            damage: 27000,
            runes: {
              primary: "7201_Precision",
              secondary: "7200_Domination",
              keystone: "PressTheAttack",
            },
          },
        ],
        objectives: {
          ally: {
            barons: 1,
            dragons: ["Infernal", "Mountain", "Cloud"],
            towers: 8,
            heralds: 1,
          },
          enemy: {
            barons: 0,
            dragons: ["Ocean"],
            towers: 3,
            heralds: 1,
          },
        },
      },
    ],
  };
};
